# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0003_auto_20170130_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenshot',
            name='title',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='video',
            name='summary',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='title',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
