# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0005_auto_20170218_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenshot',
            name='screenshot_title',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
