# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0006_screenshot_screenshot_title'),
    ]

    operations = [
        
    ]
