# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0007_video_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_title',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
