# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0008_video_video_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='summary',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
