# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 18:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_remove_device_devicename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicemodel',
            name='device',
        ),
        migrations.AddField(
            model_name='device',
            name='device_model',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='device.DeviceModel'),
            preserve_default=False,
        ),
    ]
