# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0004_auto_20161019_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='heartbeat',
            field=models.BooleanField(default=False),
        ),
    ]
