# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 18:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0008_auto_20161023_1831'),
        ('device', '0005_device_heartbeat'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='facility',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='facility.facility'),
        ),
    ]
