# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 18:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0005_downloadedapp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloadedapp',
            name='application',
        ),
        migrations.RemoveField(
            model_name='downloadedapp',
            name='device',
        ),
        migrations.DeleteModel(
            name='downloadedApp',
        ),
    ]
