# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 02:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0035_auto_20170327_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicefacilitylist',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facility.Facility'),
        ),
    ]
