# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 18:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='portaluser',
            name='facility',
        ),
        migrations.RemoveField(
            model_name='portaluser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='portaluser',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='notification',
        ),
        migrations.DeleteModel(
            name='PortalUser',
        ),
    ]
