# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 16:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0002_profile_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='profile',
            new_name='user',
        ),
    ]
