# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0003_auto_20161019_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='facility_administrator',
            field=models.BooleanField(default=False),
        ),
    ]
