# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0004_user_facility_administrator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='facility_administrator',
            new_name='is_facility_administrator',
        ),
        migrations.AddField(
            model_name='user',
            name='is_publisher',
            field=models.BooleanField(default=False),
        ),
    ]
