# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0005_auto_20161020_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
