# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 18:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facility', '0007_auto_20161023_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_facility_administrator', models.BooleanField(default=False)),
                ('is_publisher', models.BooleanField(default=False)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facility.facility')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='portaluser',
            name='facility',
        ),
        migrations.RemoveField(
            model_name='portaluser',
            name='groups',
        ),
        migrations.DeleteModel(
            name='PortalUser',
        ),
    ]
