# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 15:08
from __future__ import unicode_literals

import application.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('operatingSystem', models.CharField(default='Android', max_length=40)),
                ('version', models.CharField(max_length=40)),
                ('partNumber', models.CharField(max_length=15)),
                ('pricePerMonth', models.FloatField()),
                ('description', models.TextField()),
                ('recent_updates', models.TextField(null=True)),
                ('icon', models.ImageField(upload_to=application.models.app_directory_path)),
                ('banner', models.ImageField(upload_to=application.models.app_directory_path)),
                ('applicationFile', models.FileField(upload_to=application.models.app_directory_path)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('number_of_downloads', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AppModelList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Application')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('body', models.TextField(max_length=1000)),
                ('rating', models.PositiveIntegerField(null=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Application')),
            ],
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=application.models.app_directory_path)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Application')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to=application.models.app_directory_path)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Application')),
            ],
        ),
    ]
