# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 17:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('device', '0001_initial'),
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appmodellist',
            name='device_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.DeviceModel'),
        ),
        migrations.AddField(
            model_name='application',
            name='platform',
            field=models.ManyToManyField(through='application.AppPlatformList', to='application.Platform'),
        ),
        migrations.AddField(
            model_name='application',
            name='valid_device_models',
            field=models.ManyToManyField(through='application.AppModelList', to='device.DeviceModel'),
        ),
    ]
