# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0004_auto_20161019_1857'),
        ('application', '0002_appmodellist_device_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='valid_device_models',
            field=models.ManyToManyField(through='application.AppModelList', to='device.DeviceModel'),
        ),
    ]
