# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 00:45
from __future__ import unicode_literals

import application.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_application_valid_device_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppPlatformList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('icon', models.ImageField(upload_to=application.models.platform_path)),
            ],
        ),
        migrations.RemoveField(
            model_name='application',
            name='operatingSystem',
        ),
        migrations.AddField(
            model_name='application',
            name='developer',
            field=models.CharField(default='PDi', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appplatformlist',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Application'),
        ),
        migrations.AddField(
            model_name='appplatformlist',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Platform'),
        ),
        migrations.AddField(
            model_name='application',
            name='platform',
            field=models.ManyToManyField(through='application.AppPlatformList', to='application.Platform'),
        ),
    ]
