# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20161105_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='msrp',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
