# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0002_auto_20170125_1046'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portaluser',
            name='facility',
            field=models.ManyToManyField(to='facility.facility'),
        ),
    ]
