# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 16:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_portaluser_facility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.DeleteModel(
            name='notification',
        ),
    ]
