# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 03:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0002_auto_20170125_1046'),
        ('profiles', '0035_auto_20170330_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portaluser',
            name='facility',
        ),
        migrations.AddField(
            model_name='portaluser',
            name='facility',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='facility.Facility'),
            preserve_default=False,
        ),
    ]
