# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 16:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_auto_20170116_1712'),
    ]

    operations = [
        
    ]
