# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 04:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0025_auto_20170222_2041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='device_model',
            new_name='model',
        ),
        migrations.AlterField(
            model_name='device',
            name='facility',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='facility.Facility'),
        ),
    ]
