# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0032_auto_20170327_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='device_model',
        ),
        migrations.AddField(
            model_name='device',
            name='model',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='android_id',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
