# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 04:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0002_auto_20170125_1046'),
        ('device', '0040_auto_20170330_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='facility',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='facility.Facility'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='devicefacilitylist',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facility.Facility'),
        ),
    ]
